DX-2325 Overhaul Sample for New SDK
Bandwidth-Samples/messaging-send-receive-sms-python pull request #1
Opened 2021-12-09 21:03 UTC by ckoegel

2022-01-11 20:44 UTC, ajrice6713 submitted a review, later dismissed

2022-01-11 22:05 UTC, hamermike requested changes

2022-01-11 22:05 UTC, hamermike commented on main.py
> +    response = messages_api_instance.create_message(    # needs to be updated*********
```suggestion
    response = messages_api_instance.create_message( # needs to be updated*********
```

2022-01-11 22:05 UTC, hamermike commented on main.py
> +    message_body = MessageRequest(  # needs to be updated*********
```suggestion
    message_body = MessageRequest( # needs to be updated*********
```

2022-01-11 22:05 UTC, hamermike commented on main.py
> +@app.post('/sendMessage')   # Make a POST request to this URL to send a text message.
```suggestion
@app.post('/sendMessage') # Make a POST request to this URL to send a text message.
```

2022-01-11 22:05 UTC, hamermike commented on main.py
> +@app.post('/callbacks/outbound/messaging/status')   # This URL handles outbound message status callbacks.
```suggestion
@app.post('/callbacks/outbound/messaging/status') # This URL handles outbound message status callbacks.
```

2022-01-11 22:05 UTC, hamermike commented on main.py
> +@app.post('/callbacks/inbound/messaging')   # This URL handles inbound message callbacks.
```suggestion
@app.post('/callbacks/inbound/messaging') # This URL handles inbound message callbacks.
```

2022-02-01 18:27 UTC, hamermike approved these changes

2022-02-01 18:27 UTC, hamermike commented on main.py
> +# ***************needs to be changed when sdk becomes python package
```suggestion
# TODO: Needs to be changed when the SDK becomes python package.
```

2022-02-01 18:27 UTC, hamermike commented on main.py
> +configuration = openapi_client.Configuration(     # needs to be updated*********  # Configure HTTP basic authorization: httpBasic
```suggestion
configuration = openapi_client.Configuration(     # TODO:  # Configure HTTP basic authorization: httpBasic
```

2022-02-01 18:27 UTC, hamermike commented on main.py
> +api_client = openapi_client.ApiClient(configuration)  # needs to be updated*********
```suggestion
api_client = openapi_client.ApiClient(configuration)  # TODO:
```

2022-02-01 18:27 UTC, hamermike commented on main.py
> +messages_api_instance = MessagesApi(api_client) # needs to be updated*********
```suggestion
messages_api_instance = MessagesApi(api_client) # TODO:
```

2022-02-01 18:27 UTC, hamermike commented on main.py
> +    message_body = MessageRequest( # needs to be updated*********
```suggestion
    message_body = MessageRequest( # TODO:
```

2022-02-01 18:27 UTC, hamermike commented on main.py
> +    response = messages_api_instance.create_message( # needs to be updated*********
```suggestion
    response = messages_api_instance.create_message( # TODO:
```

2022-02-02 22:09 UTC, hamermike approved these changes, later dismissed

2022-02-17 16:26 UTC, ckoegel commented on README.md
> +You can view your public URL at `http://127.0.0.1:8000` after ngrok is running.  You can also view the status of the tunnel and requests/responses here.
```suggestion
You can view your public URL at `http://127.0.0.1:4040` after ngrok is running.  You can also view the status of the tunnel and requests/responses here.
```

2024-09-17 14:59 UTC, closed without merging